### ISSUE TITLE
San Franciso Passenger Count Data, time > 24:XX:XX

### ISSUE THREAD

**Issue by 3dmashup** [swissnexSF/Urban-Data-Challenge#2]
The San Francisco Passenger Count data has invalid time in  columns P, Q the time starts exceeding 24:00:00 at around line 19998 thru 20080.  There may be other places too. Are these times using a 24 hr clock? Should they not be rolled over to 00:XX:XX  when the time exceeds 24:00:00?

Please can someone clarify this unit of time.

**Comment by poezn** [comment]
Here's the answer from Chris (of SFMTA) on the Google Groups page:

When the times roll past 24:00 it just means that it is past midnight on the next day.  You may want covert, for example, October 1st 24:33 to October 2nd 00:33.

As an FYI, our data does this because we classify weekday service separate from Saturday and Sunday service.  For our internal purposes, Friday 24:33 needs to be classified as weekday service and not Saturday service, as an example.

https://groups.google.com/forum/?fromgroups=#!msg/urban-data-challenge/0LAec7QaV_4/EEw01GiabGcJ
